package dtu.appliedcrypto.chatapplication_server.crypto;

public enum DHState {
  KEY_EXCHANGE_NOT_INITIALIZED, KEY_EXCHANGE_INITIALIZED, KEY_ESTABLISHED, CERT_EXCHANGE_INITIALIZED,
  CERT_EXCHANGE_NOT_INITIALIZED
}